### PR TITLE
Fixed: rack server unable to start. Added installation instructions

### PR DESCRIPTION
**Pull request by seanhess**
I added some instructions to get the server running and fixed a runtime error in one of the files.

### CODE REVIEW

**Comment by simonista** [comment]
Hey @seanhess, thanks for the PR.  We actually have done a bunch of work on this code in preparation for the upcoming contest (including pulling this server out into a separate gem/repo).  We'll try to get it pushed up after the competition.

**Comment by seanhess** [comment]
Cool. I figure that other folks might want to prepare by attempting the
previous year's final. Might be worth merging in the meantime? (The code as
written doesn't run for me)

**Comment by jcmoore** [comment]
Big thanks to you @seanhess for providing easy deployment setup/instructions

**Comment by simonista** [comment]
No longer relevant.

**Pull request closed without merging**
